apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared  
  # annotations:
  #     prometheus.io/scrape: 'true'
  #     prometheus.io/port:   '3000'
spec:
  selector: 
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  # namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - name: grafana
          containerPort: 3000
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1000m"
        #   requests: 
        #     memory: "1Gi"
        #     cpu: "500m"
      #   volumeMounts:
      #     - mountPath: /var/lib/grafana
      #       name: grafana-storage
      #     - mountPath: /etc/grafana/provisioning/datasources
      #       name: grafana-config
      #       readOnly: false
      # volumes:
      #   - name: grafana-storage
      #     emptyDir: {}
      #   - name: grafana-config
      #     configMap:
      #         defaultMode: 420
      #         name: grafana-config


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: grafana
# spec:
#   selector:
#     matchLabels:
#       app: grafana
#   template:
#     metadata:
#       labels:
#         app: grafana
#     spec:
#       containers:
#         - name: grafana
#           image: grafana
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
# spec:
#   selector:
#     app: grafana
#   ports:
#     - port: 3000
#   type: LoadBalancer