apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: pass1234
  INFLUXDB_DB: influxdb
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: user1234