
apiVersion: v1
kind: Service
metadata:
  name: nginx-depl
  labels:
    app: app-nginx
spec:
  type: ClusterIP
  selector:
    app: app-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443