
apiVersion: v1
kind: Service
metadata:
  name: nginx-depl
  labels:
    app: app-nginx
spec:
  type: LoadBalancer
  selector:
    app: app-nginx
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP