# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wordpress-persistent-storage
#   labels:
#     app: wordpress
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteMany
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: /private/var/vm
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minikube
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-persistent-storage
#   labels:
#     app: mysql
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteMany
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: /private/var/vm
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minikube

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wordpress-persistent-storage
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 128Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"