apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: local_monitoring
  INFLUXDB_URL: http://ip_service:8086
  INLUXDB_USER: user
  INLUXDB_USER_PASSWORD: pass1234