apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://192.168.99.153:8086
  INLUXDB_USER: user
  INLUXDB_USER_PASSWORD: user1234