apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - name: telegraf
    port: 8125
    targetPort: 8125
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: monitoring
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf
        name: telegraf
        imagePullPolicy: Never
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
        envFrom:
        - secretRef:
            name: telegraf-secret
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
